function makematlabmov_path(thePath,dataFolder,filename,movieName)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% This function will generate a spatial plot along the specified path of
% the neuron geometry
%-------------------------------------------------------------------------%
% Input: filename of SWC file, movieName is the name of the .mp4, thePath
% is a path generated by the pathAtoB.m function, the dataFolder is
% generated when running the neuronsim i.e. 0Ref2.0000000 is an example
% name of the folder generated by the neuronsim
%
% Output: the movie will be saved to the path specified in movieName
%-------------------------------------------------------------------------%
%   Written by James Rosado 02/19/2021
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% this loads the time stamps from the simulation
load(sprintf('%s/time.mat',dataFolder),'t');
% get the coordinates and radii for plotting purposes
[~,~,~,coords,r,~]=readSWC(filename);
% this is how I define the marker sizes
markerSizes = 20.*r./max(r);
fig=figure('units','normalized','outerposition',[0 0 0.4 0.6]);

% this is for recording the movie
v = VideoWriter(sprintf('%s.mp4',movieName),'MPEG-4');
open(v)

% set the color bar range
cbarmin = -5;
cbarmax = 50;

for i=1:100:length(t)-1
    % this reads the voltage data .dat files that are in dataFolder
    vm = readmatrix(sprintf('%s/data/vm_t%i.dat',dataFolder,i));
    vm = vm(thePath);
    scatter3(coords(thePath,1),coords(thePath,2),coords(thePath,3),markerSizes(thePath),'filled','CData',vm*1e3);
    % this is for labeling
    xlabel(sprintf('{\\mu}m'))
    ylabel(sprintf('{\\mu}m'))
    % you may need to specify the width or height of the plot
    xlim([-200,200])
    %title the figure and show time progression
    title(sprintf('MatLab Code, t = %0.3f ms',t(i)*1e3));
    set(gca,'Color', [0.35 0.35 0.35])
    set(gca,'GridColor',[1 1 1])
    grid on
    caxis([cbarmin cbarmax])
    colormap('jet')
    colorbar
    c = colorbar;  
    c.Label.String="mV";
    view(2)
    drawnow
    
    % save the frame to video file
    thisframe=getframe(fig);
    writeVideo(v, thisframe);
end
% always make sure to close the video file when you are done!
close(v)